[env:custom_esp32s3]
platform = espressif32
board = esp32s3_4mb
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    bblanchon/ArduinoJson@^6.19.4
    ottowinter/ESPAsyncWebServer-esphome@^3.0.0
    esphome/AsyncTCP-esphome@^1.2.2
    adafruit/Adafruit NeoPixel@^1.12.0

build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D USE_OLED_DISPLAY

board_build.filesystem = littlefs
data_dir = data